### ISSUE TITLE
Recipes are not visible

### ISSUE THREAD

**Issue by Autodidax86** [Boomflex/JustNotEnoughMods2#1]
Hi,
somehow not all recipes are visible (e.g. mekanism, solargeneration, ...) when playing on a server. Local games work fine.

Version: 0.3.1
Minecraft-Version: 1.15.1
(modded) forge-30.0.42

it also seems that there is no ore generation on server side...

**Comment by Boomflex** [comment]
Hi,

I just created a server and all recipes are visible...

Which recipes you having issue with?
