### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by FawneBartley** [Boomflex/JustNotEnoughMods2#10]
Hey All,

When trying to open the modpack the game crashes with the below message
![image](https://user-images.githubusercontent.com/14330070/74786868-db725f80-5301-11ea-918b-f19b5f846829.png)

The pack is on the latest version and the only thing I have changed is the amount of memory being used to 7GB. (Please note the crashing still happens when not changing the memory amount)

I would love to try the modpack however I haven't been able to because of this issue.

**Comment by Boomflex** [comment]
Use a different launcher other than Twitch App.

Try ATLauncher or GDLauncher.
