### ISSUE TITLE
Tick loop when starting server

### ISSUE THREAD

**Issue by lukaszMarcinkowski95** [Boomflex/JustNotEnoughMods2#17]
Don't know what to do.. 
I tried deleting MineColonies and Structurize but server won't start without this mods.
I already tried to replace Structurize with new version but still doesn't work.
I tried the same with MineColonies..

Can someone help me?

PS. Singleplayer is working, but server... as You guys see

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 09/03/2020, 02:08
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:48) ~[?:0.10.271-ALPHA] {re:classloading}
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:108) ~[?:0.10.271-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.loadSchematicsForPrefix(Structures.java:333) ~[?:0.10.271-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.management.Structures.loadStyleMapsJar(Structures.java:238) ~[?:0.10.271-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.management.Structures.loadStyleMaps(Structures.java:145) ~[?:0.10.271-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.management.Structures.init(Structures.java:122) ~[?:0.10.271-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.event.EventSubscriber.onServerStarting(EventSubscriber.java:58) ~[?:0.10.271-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_267_EventSubscriber_onServerStarting_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:414) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:844) [?:?] {}
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.lang.ClassLoader.findClass(ClassLoader.java:709) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:92) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?] {}
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.9.185-xxxx-std-ipv6-64
	Java Version: 9, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1698628248 bytes (1619 MB) / 2677276672 bytes (2553 MB) up to 5234491392 bytes (4992 MB)
	CPUs: 2
	JVM Flags: 15 total; -XX:+AggressiveOpts -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Xmx5G -Xms2G
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		incontrol-1.15-4.0.1.jar InControl {incontrol@1.15-4.0.1 DONE}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		IndustrialAgriculture[Core]-1.15.2-1.5.4.jar Industrial Agriculture {industrialagriculture@1.15.2-1.5.4 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		noautojump-1.15.2-1.jar No Auto-Jump {noautojump@1.15.2-1 DONE}
		IronJetpacks-1.15.2-3.0.0.jar Iron Jetpacks {ironjetpacks@3.0.0 DONE}
		CoffeeSpawner-1.15.1-6.0.0.jar Coffee Spawner {coffeespawner@1.15.1-6.0.0 DONE}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 DONE}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		dankstorage-2.5.jar Dank Storage {dankstorage@2.5 DONE}
		Powah-1.15.2-1.1.6.jar Powah {powah@1.1.6 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 DONE}
		Morpheus-1.15.2-4.2.47.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.9.11.403.jar Mekanism: Generators {mekanismgenerators@9.9.11 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		carpetstairsmod-mc1.15-v1.3.jar Carpet Stairs Mod {carpetstairsmod@1.1 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		absentbydesign-1.15.2-1.0.5 .jar Absent By Design Mod {absentbydesign@1.15.2-1.0.5  DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		PackMenu-1.15.2-1.1.7.jar Pack Menu {packmenu@1.1.7 DONE}
		industrial-foregoing-1.15.2-2.2.1-f27c515.jar Industrial Foregoing {industrialforegoing@2.2.1 DONE}
		Industrial Agriculture[Silent's Mechanisms]-1.15.2-1.5.3.jar Industrial Agriculture Plugin-Silent's Mechanisms {iapsm@1.15.2-1.5.3 DONE}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE}
		Lollipop-1.15.2-1.0.8.jar Lollipop {lollipop@1.0.8 DONE}
		mining_dimension-1.15.2-1.0.1.jar Mining World {mining_dimension@1.15.2-1.0.1 DONE}
		SilentGear-1.15.2-1.5.2+77.jar Silent Gear {silentgear@1.5.2+77 DONE}
		Patchouli-1.15.2-1.2-27.jar Patchouli {patchouli@1.15.2-1.1-25 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE DONE}
		tanknull-1.7.jar Tank Null {tanknull@1.7 DONE}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		tombstone-4.2.4-1.15.2.jar Corail Tombstone {tombstone@4.2.4 DONE}
		NaturesAura-23.1.jar Nature's Aura {naturesaura@version DONE}
		MekanismTools-1.15.2-9.9.11.403.jar Mekanism: Tools {mekanismtools@9.9.11 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		nosoliciting-1.1.jar No Soliciting {nosoliciting@1.1 DONE}
		BetterBurning-1.15.2-1.3.1.jar BetterBurning {betterburning@1.3.1 DONE}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 DONE}
		CustomWindowTitle-1.15.2-v1.0.0.jar Custom Window Title {customwindowtitle@1.0.0 DONE}
		speedyladders-1.15.2-1.jar Speedy Ladders {speedyladders@1.15.2-1 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		ServerTabInfo-1.15.2-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 DONE}
		SimpleDiscordRichPresence-1.15.2-1.2.4.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.4 DONE}
		Cyclic-1.15.2-0.1.11.jar Cyclic {cyclic@1.15.2-0.1.11 DONE}
		inftrading_1.15-1.0.jar Infinite Trading {inftrading@1.0 DONE}
		Kiwi-1.15.2-2.7.0.jar Kiwi {kiwi@2.7.0 DONE}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 DONE}
		craftingstation-3.0.5.jar Crafting Station {craftingstation@3.0.5 DONE}
		janoeo-3.1.2.jar Just Another Nether/Overworld/End Ores {janoeo@3.1.2 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		buzzierbees-1.1.4.jar Buzzier Bees {buzzierbees@1.1.4 DONE}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 DONE}
		Mekanism-1.15.2-9.9.11.403.jar Mekanism {mekanism@9.9.11 DONE}
		reap-1.12.1.jar Reap Mod {reap@1.12.1 DONE}
		invtweaks-1.15.2-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.1 DONE}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 DONE}
		NaturesCompass-1.15.2-1.8.4.jar Nature's Compass {naturescompass@1.15.2-1.8.4 DONE}
		premenuscreen-1.3.jar Pre Menu Screen {premenuscreen@1.3 DONE}
		gardentools-1.15.2-1.0.0.jar Garden Tools {gardentools@1.15.2-1.0.0 DONE}
		DimStorage-1.15.2-3.0.1.jar DimStorage {dimstorage@3.0.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.0.2-alpha.jar McJtyLib {mcjtylib@1.15-4.0.2-alpha DONE}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha DONE}
		xnet-1.15-2.0.1-alpha.jar XNet {xnet@1.15-2.0.1-alpha DONE}
		rftoolsstorage-1.15-1.0.2-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.2-alpha DONE}
		CraftTweaker-1.15.2-6.0.0.9.jar CraftTweaker {crafttweaker@6.0.0.9 DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 DONE}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 DONE}
		colouredchat-1.15.1-1.4.5.jar ColouredChat {colouredchat@1.15.1-1.4.5 DONE}
		forge-1.15.2-31.1.18-server.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b DONE}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha DONE}
		theoneprobe-1.15-2.0.1.jar The One Probe {theoneprobe@1.15-2.0.1 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		archers_paradox-1.15.2-0.3.0b.jar Archer's Paradox {archers_paradox@0.3.0b DONE}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha DONE}
		Xaeros_Minimap_20.4.0.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.4.0.1 DONE}
		JAOPCA-1.15.2-3.0.0.20.jar JAOPCA {jaopca@3.0.0.20 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		structurize-0.10.271-ALPHA.jar Structurize {structurize@0.10.271-ALPHA DONE}
		minecolonies-0.10.738-ALPHA-universal.jar Minecolonies {minecolonies@0.10.738-ALPHA DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		World-Stripper-1.7.2-1.15.1.jar World Stripper {worldstripper@1.7.2 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		Aquaculture-1.15.2-2.0.9.jar Aquaculture 2 {aquaculture@1.15.2-2.0.9 DONE}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.5.2.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.5.2 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		Ma-Essentials-1.15.2-3.0.0.jar Ma Essentials {ma-essentials@1.15.2-3.0.0 DONE}
		SolarGeneration-1.15.2-1.2.0.jar Solar Generation {solargeneration@1.2.0 DONE}
	Kiwi Modules: 
		kiwi:contributors
	Player Count: 0 / 20; []
	Data Packs: vanilla, inmemory:jaopca (incompatible), mod:absentbydesign (incompatible), mod:aiimprovements (incompatible), mod:appleskin (incompatible), mod:aquaculture, mod:archers_paradox (incompatible), mod:attributefix (incompatible), mod:backpacked (incompatible), mod:betterbedrockgenerator, mod:betterburning (incompatible), mod:bettertitlescreen, mod:bonsaitrees2, mod:buzzierbees, mod:bwncr (incompatible), mod:carpetstairsmod, mod:cloth-config2 (incompatible), mod:coffeespawner, mod:cofh_core (incompatible), mod:colouredchat (incompatible), mod:craftingstation (incompatible), mod:crafttweaker (incompatible), mod:cucumber, mod:customwindowtitle, mod:cyclic (incompatible), mod:dankstorage (incompatible), mod:dimstorage (incompatible), mod:elevatorid, mod:ensorcellation (incompatible), mod:extradisks, mod:fastbench (incompatible), mod:fastfurnace (incompatible), mod:fastleafdecay, mod:forge (incompatible), mod:gardentools (incompatible), mod:iapmekanism, mod:iapsm (incompatible), mod:incontrol (incompatible), mod:industrialagriculture, mod:industrialforegoing (incompatible), mod:inftrading (incompatible), mod:invtweaks (incompatible), mod:ironjetpacks, mod:janoeo (incompatible), mod:jaopca (incompatible), mod:jei (incompatible), mod:kiwi, mod:kleeslabs (incompatible), mod:libnonymous (incompatible), mod:lightoverlay-forge (incompatible), mod:lollipop (incompatible), mod:lostcities (incompatible), mod:ma-essentials (incompatible), mod:mcjtylib (incompatible), mod:mcwwindows, mod:mekanism, mod:mekanismgenerators, mod:mekanismtools, mod:minecolonies (incompatible), mod:mining_dimension, mod:moredragoneggs, mod:morpheus (incompatible), mod:mysticalagradditions, mod:mysticalagriculture, mod:naturesaura (incompatible), mod:naturescompass (incompatible), mod:noautojump (incompatible), mod:nosoliciting (incompatible), mod:oreexcavation (incompatible), mod:packmenu (incompatible), mod:patchouli (incompatible), mod:placebo (incompatible), mod:powah (incompatible), mod:premenuscreen, mod:randompatches (incompatible), mod:rangedpumps (incompatible), mod:reap, mod:refinedstorage (incompatible), mod:refinedstorageaddons (incompatible), mod:rftoolsbase (incompatible), mod:rftoolsbuilder (incompatible), mod:rftoolsstorage (incompatible), mod:rftoolsutility (incompatible), mod:sdrp (incompatible), mod:servertabinfo (incompatible), mod:silentgear (incompatible), mod:silentlib (incompatible), mod:silents_mechanisms (incompatible), mod:solargeneration (incompatible), mod:speedyhoppers (incompatible), mod:speedyladders, mod:storagedrawers (incompatible), mod:structurize (incompatible), mod:swingthroughgrass (incompatible), mod:tanknull (incompatible), mod:theoneprobe (incompatible), mod:titanium (incompatible), mod:tombstone, mod:valkyrielib (incompatible), mod:worldstripper (incompatible), mod:wstweaks (incompatible), mod:xaerominimap, mod:xaeroworldmap, mod:xnet (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Boomflex** [comment]
Pack updated multiple times since. 

Try again.
