### ISSUE TITLE
Mystical Agriculture & the broken addons.

### ISSUE THREAD

**Issue by cubbiemi** [Boomflex/JustNotEnoughMods2#22]
Hi.
Long time player, first time complainer.

Started in 0.5.2
Silicon Seed (few others) - Show in JEI, uncraftable no recipe shown.

Several of the plants for materials from Silent's (possibly other) mods don't have the short name its like plant.material.somethingsomething when you look at them planted rather than Steel Seed, Iron Seed (examples from the top of my head not actual problematic seed names).

Please & Thank You.

**Comment by Boomflex** [comment]
Mod issue. 

Have reported to dev.
