### ISSUE TITLE
Corrupted chunks? Minecraft server crashes when certain players join/go to certain places

### ISSUE THREAD

**Issue by Fallen322** [Boomflex/JustNotEnoughMods2#24]
Since this modpack is the newest version of minecraft that can be allowed to mod. I have no clue how to fix this issue, if someone can help me with fixing corrupt chunks or maybe finding the reason why these places crash randomly, that would be really appreciated

**Comment by Boomflex** [comment]
Upload crash log to pastebin and paste it here.
