### ISSUE TITLE
Minecolonies crashes Server/World

### ISSUE THREAD

**Issue by angrylightning** [Boomflex/JustNotEnoughMods2#29]
When players try placing any blocks from the minecolonies mod my server crashes. I have tested this on a single player world and it's doing the same thing to that world. I'm using the newest version of the modpack download through curse and using the twitch launch to play the pack. All I can get from the crash logs is it causing the server to lag to the point it auto restarts. Any help would be greatly appreciated this the first time I've hosted a server so I'm not sure what to try.

**Comment by Boomflex** [comment]
Please report it to the Minecolonies dev.

Thanks
