### ISSUE TITLE
Connection closed - mismatched mod channel list

### ISSUE THREAD

**Issue by TraitsJack** [Boomflex/JustNotEnoughMods2#3]
Unable to connect to server
Incompatible FML modded server
Server network message list is not compatible

[32m[13:04:40] [User Authenticator #1/INFO] [minecraft/ServerLoginNetHandler]: UUID of player JackTraits is 026c0b14-5a3c-4513-8093-451a3c3961b2
[m[32m[13:04:40] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@ffeed67[id=026c0b14-5a3c-4513-8093-451a3c3961b2,name=JackTraits,properties={textures=[com.mojang.authlib.properties.Property@23a59854]},legacy=false] (/192.168.1.208:56441) lost connection: Disconnected
[m

**Comment by Boomflex** [comment]
Can you upload the whole latest.log to Pastebin and post it please.

**Comment by TraitsJack** [comment]
https://pastebin.com/7q8nyDBQ
Here is the link not sure hot to paste it here

**Comment by Boomflex** [comment]
Very odd...

Not seeing anything blatantly wrong.

Ok, retry downloading the pack from Twitch, just incase something went
wrong when downloading.

**Comment by TraitsJack** [comment]
Download server pack or just install?

**Comment by TraitsJack** [comment]
Not sure if this is anything server-setup-config.yaml  The modpackURL version is 0.0.0.4, shouldn't it be 0.0.3.1?

**Comment by TraitsJack** [comment]
Here is the latest.log Client side
https://pastebin.com/xyD9KRjv

**Comment by Boomflex** [comment]
Yes, it should be 0.3.1

I am reuploading the server files now.

Give it 10 mins and redownload

**Comment by TraitsJack** [comment]
Okay I will wait and try it out again

**Comment by Boomflex** [comment]
Try this and let me know :)

https://www.curseforge.com/minecraft/modpacks/just-not-enough-mods-2/files/2872652

**Comment by TraitsJack** [comment]
Woot! it worked! Thank you so much for taking the time to help out :D

**Comment by Boomflex** [comment]
Awesome!

No worries man :)
