### ISSUE TITLE
Double Backpack Bug

### ISSUE THREAD

**Issue by Nicole-Evermore** [Boomflex/JustNotEnoughMods2#33]
Our server is on 0.5.3. I put on both types of backpack in the pack at the same time and that killed the server. When I got on again, it ran smoothly until I tried to view my inventory, and the server died again. Based on the fact that my old chestplate was still on the ground, I assume I was still wearing both backpacks and that's what is killing it. I'm going to kill myself on the server the next time it comes up, and thank the fact we didn't have keep inventory on.

New Edit: Turns out it's just the Quark backpack causing the issue. Removing the other backpack and putting on the Quark one once again crashed the server.

**Comment by Perlo0ung** [comment]
Quark backpack crashes my server too when opening inventory.
