### ISSUE TITLE
all is broken!!

### ISSUE THREAD

**Issue by numerik1871** [Boomflex/JustNotEnoughMods2#34]
All is broken, my crops don't grow, the chunks don't work in furnace, all chunks! backpack bugs... the versions is 0.6.0a. the bugs start with the 0.6.0! before that, everything work flawlessly, but now is impossible to return back, with or without my save... Help me please!

**Comment by Boomflex** [comment]
Crops will grow, just make sure you read the packs changelog... they now require a Crux underneath. 

The chunks part I will look in to. 

The backpack, you’ll have to be a little more specific.
