### ISSUE TITLE
Mysticalagriculture seed can't growth

### ISSUE THREAD

**Issue by Ruisi-Lu** [Boomflex/JustNotEnoughMods2#35]
version : JNEM2 0.6.0a
environment : local and server
Mysticalagriculture's seed can't use any way to growth.

used:
- Supremium Growth
- Bone Meal

![image](https://user-images.githubusercontent.com/34283364/80198954-600b9200-8653-11ea-8de4-4ec4bef33e37.png)

**Comment by Boomflex** [comment]
Read the changelog. 

Majority of seeds now need a crux underneath the farmland. 

In the case of dirt, you need to place coarse dirt under the farmland.

**Comment by Ruisi-Lu** [comment]
- 

> Read the changelog. Majority of seeds now need a crux underneath the farmland. In the case of dirt, you need to place coarse dirt under the farmland.
> […](#)
> Sent from my iPhone
> On 24 Apr 2020, at 10:45, Ruisi ***@***.***> wrote: ﻿ version : JNEM2 0.6.0a environment : local and server Mysticalagriculture's seed can't use any way to growth. used: Supremium Block Bone Meal — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks. I place coarse dirt under the farmland, and successful.
But bone meal can't accelerate growth.
I am not sure that is a bug, or a setting.

**Comment by Boomflex** [comment]
Bone meal has never worked on Myst Agri crops.

You have to use either the watering can or the special growth powder from the mod itself.
