### ISSUE TITLE
Unable to collect souls for Blazes or Magma cubes in soul jars

### ISSUE THREAD

**Issue by Anniebe11** [Boomflex/JustNotEnoughMods2#37]
modpack version 0.6.0a

I have a soul jar (usually several) in my inventory
I am killing the blazes and magma cubes with the soulium dagger

the soul jars all appear to remain empty
one soul jar becomes bugged and will no longer accept any soul

I have successfully collected souls from skeletons, zombies, endermen, spiders, creepers, cows, pigs, chickens, sheep, rabbits and squid.

I believe I may have tried witches and failed, but since the only thing that could be made from witch essence is witch spawn eggs I thought perhaps this was deliberate.

both blaze and magma cube seeds have other uses so it would be good to be able to make them

**Comment by Anniebe11** [comment]
also not able to collect shulker souls

**Comment by Boomflex** [comment]
All seem to be working on the official server.

Will have to mark this down as unreproducible.

Will keep an eye on any other comments about it.
