### ISSUE TITLE
cannot make block of aluminum steel

### ISSUE THREAD

**Issue by Anniebe11** [Boomflex/JustNotEnoughMods2#38]
there is no recipe for the block of aluminum steel.  the usual 3x3 ingots pattern does not work.  this block is used as a crux for the aluminum steel seeds so the seeds cannot be farmed

**Comment by Boomflex** [comment]
Already reported.

Fixed in 0.6.1

**Comment by Boomflex** [comment]
![image](https://user-images.githubusercontent.com/22868795/80699851-9b371680-8ad4-11ea-8990-08592a6fc53a.png)


![image](https://user-images.githubusercontent.com/22868795/80699858-a0946100-8ad4-11ea-8961-a8d2e0e49cd5.png)
