### ISSUE TITLE
Mystical Agriculture broken?

### ISSUE THREAD

**Issue by HalperinOrganix** [Boomflex/JustNotEnoughMods2#46]
All the seeds I plant for Mystical Agriculture don't grow on farmland or in a Garden Cloche, sitting there with a Prudentium Watering Can and 12 Growth Accelerators does nothing, Essence Farmland says disabled by mod author.

Not sure if I'm just retarded, please help.

**Comment by Xendisabu** [comment]
It isn't broken, to make the modpack more balanced, the author is using cruxes.  You can see the full list here: [https://discordapp.com/channels/659654158932246529/659654158932246532/724430158215512086](https://discordapp.com/channels/659654158932246529/659654158932246532/724430158215512086) For the cruxes, you just need to place the crux block directly under the farmland block that has the corresponding seed planted on it. For and cruxes listed as "" you can either leave the first block empty, or use accelerators as normal.

**Comment by HalperinOrganix** [comment]
Thank you very much, I don't think I would have ever figured that out.
