### ISSUE TITLE
Mod packs keeps restarting the server

### ISSUE THREAD

**Issue by gabmar4** [Boomflex/JustNotEnoughMods2#5]
Last night i installed the server and could play with some friends and today the server keeps restarting over and over until it does so 11 times.Is there any fix?

**Comment by gabmar4** [comment]
So there was a cut on power and my local ip changed ,making the portforward useless. Fixed it by changing the portforward ,sorry for creating this post.

**Comment by Boomflex** [comment]
Hey sorry just seen this, and pleased it is now sorted :)
