### ISSUE TITLE
Pack instantly crashing on startup.

### ISSUE THREAD

**Issue by Miyazono1** [Boomflex/JustNotEnoughMods2#8]
i'll open the pack from the twitch launcher, and the open the pack's instance from the MC launcher, and it instantly crashes.  this is not the only modpack it's happening with, as well. but other packs opened just fine. it might not be an issue with the pack, but any insight on the issue is appreciated. i attached the latest.log from the last run of the pack if that helps.
[latest.log](https://github.com/Boomflex/JustNotEnoughMods2/files/4189552/latest.log)

**Comment by Boomflex** [comment]
This is a Launcher issue and not a pack issue.

Try GDLauncher or ATLauncher methods.
