### ISSUE TITLE
0.4.4 Server Files Meeting error on startup

### ISSUE THREAD

**Issue by chaoschao11** [Boomflex/JustNotEnoughMods2#9]
Based on the error it seems like a mod it is trying to install is borked

**Comment by Boomflex** [comment]
I just ran the Install myself and it loaded first time.

Any more information? Crash log? Screenshot?

**Comment by Boomflex** [comment]
I just noticed an error which could lead to a error but it doesn't for me...

Try these new files: https://www.curseforge.com/minecraft/modpacks/just-not-enough-mods-2/files/2880839

**Comment by chaoschao11** [comment]
Hey sorry, thought I attached the error screenshot. Tried the new files and it works!

Cheers!
